MODEL:
  DEVICE: "cuda:0"
  NUM_WORKERS: 0
  BATCH_SIZE: 8
  NUM_JOINTS: 21
  PRETRAIN_WEIGHT: None
    # HM_NET_PATH: "./model/FreiHAND_BoneLoss_models/net_hm.pth"
    # MESH_NET_PATH: "./model/pretrained_models/net_feat_mesh.pth"
    # POSE_NET_PATH: "./model/pretrained_models/net_mesh_pose.pth"
    # MLP_NET_PATH: "./model/FreiHAND_BoneLoss_models/mlp.pth"
GRAPH:
  TEMPLATE_PATH: "./data/0214_lowP_vn_g.0001.obj"
EVAL:
  SAVE_DIR: "./output"
  SAVE_BATCH_IMAGES_PRED: True
  PRINT_FREQ: 1
  SAVE_POSE_ESTIMATION: True
  DATASET: "FreiHAND_test"
